### PR TITLE
Check alternate SSL bundle path

### LINKED ISSUE #6: SSL connect error with Nixie
Hello,

I'm trying to replace my usage of nix-portable with Nixie, but have stumbled upon a problem that the `nix` script can't download the cache:

```
$ ./nix shell nixpkgs#hello
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 259 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 576 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 1102 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 2446 ms
error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35)
```

Is there a known workaround for it? or do you have any ideas how I could debug it further?

Thanks!

### PR DESCRIPTION
**Pull request by Thesola10**
This fixes #6

In the future, a list of known OpenSSL paths could be checked dynamically

### CODE REVIEW

**Comment by twesterhout** [comment]
Hm... no, I'm getting SSL errors again

**Comment by twesterhout** [comment]
Oh wait, I have to regenerate `nix` manually, don't I?

**Comment by Thesola10** [comment]
Normally you'd run `nixie update` to refresh the `nix` in this branch, i'll do that for you real quick

**Comment by twesterhout** [comment]
Still the same :(

```
twest@int4:~/nixie$ git pull origin fix-ssl
From https://github.com/nixie-dev/nixie
 * branch            fix-ssl    -> FETCH_HEAD
Updating 5db2b26..85c1556
Fast-forward
 nix | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
twest@int4:~/nixie$ ./nix shell nixpkgs#mpi
warning: error: unable to download 'https://cache.nixos.org/nar/0m38qzijk1z3v3lym81rmkih4x3zqz053nhijvp7ywl0gff466xk.nar.xz': SSL connect error (35); retrying in 340 ms
```

**Comment by Thesola10** [comment]
i'm an idiot, i updated with my installed version of Nixie instead of this branch so it just updated the script with the previous release

**Comment by twesterhout** [comment]
That did it! Thanks for the quick fix.

**Pull request merged**
